// Generated by CoffeeScript 1.7.1

/*
    自古华山一条路
 */
var changeNumbers, date, exports, fill, kids, mood, plus, sum, trigger,
  __slice = [].slice;

fill = function(container, liquid) {
  if (liquid == null) {
    liquid = 'coffee';
  }
  return "Filling the " + container + " width " + liquid;
};

console.log(fill('div'));

kids = {
  brother: {
    name: 'Max',
    age: 11
  },
  sister: {
    name: 'Ida',
    age: 9
  }
};

changeNumbers = function() {
  var inner, outer;
  inner = -1;
  return outer = 10 + inner;
};

console.log(changeNumbers());

exports = exports != null ? exports : this;

if (true) {
  mood = 3;
}

if (mood === 3 && true) {
  console.log(mood);
} else {
  console.log('good work');
}

date = mood > 2 ? 2 : 4;

console.log(date);

plus = function(a, b) {
  if (a == null) {
    a = 2;
  }
  if (b == null) {
    b = 3;
  }
  return a + b;
};

console.log(plus());

sum = function() {
  var nums, result;
  nums = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  result = 0;
  nums.forEach(function(num) {
    return result += num;
  });
  return result;
};

console.log(sum(1, 4, 8));

trigger = function() {
  var events;
  events = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  events.splice(2, 0, 'a');
  return events;
};

console.log(trigger(1, 2, 3, 4));


